apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kotlin-ingress-helm
  annotations:
    kubernetes.io/ingress.class: nginx
{{- if .Values.ingress.extraAnnotations }}
{{ toYaml .Values.ingress.extraAnnotations | indent 4 }}
{{- end }}
spec:
  rules:
    - host:
      http:
        paths:
          - path: /(.*)
            backend:
              serviceName: kotlin-service
              servicePort: 80